version: "3"
services:
  exercise5:
    build: .
    ports:
      - "9005:9005"
    links:
      - messageapp
      - mongodb1
      - mongodb2
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb1:
    image: mongo
    volumes:
      - ./data/db1:/data/db
    ports:
      - 27017:27017
  mongodb2:
    image: mongo
    volumes:
      - ./data/db2:/data/db
    ports:
      - 27018:27017